window_title: "MOFOxPred"
page_title: "MOFOxPred"

about_section_title: "About MOFOxPred"

templates:
  how_to_cite: "how_to_cite.html"
  about: "about.html"

use_upload_structure_block: True

additional_accordion_entries:
#  - header: "What is this?"
#    template_page: what_is.html
  - header: "Acknowledgements"
    template_page: ack.html