name: Docker Image Build CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build-docker.sh && cd oximachine && ./build_docker.sh && ./run_docker.sh &&  curl -X POST --data "examplestructure=sno" http://localhost:8091/process_example_structure/ > example.html && grep -F "Sn" example.html || ( cat example.html ; exit 1 ) 
      
