name: Docker Image Build CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build-docker.sh && cd oximachine && ./build_docker.sh && ./run_docker.sh &&  ../test/wait-for-it.sh localhost:8091 -t 120 && sleep 15 && Kevin 19:22
curl -X POST --data 'examplestructure=sno' http://localhost:8091/process_example_structure/ > example.html && grep -F "Sn" example.html && cat example.html
      
